#langchain4j:
#  ollama:
#    chat-model:
#      base-url: http://localhost:11434
#      model-name: deepseek-r1:1.5b
#    streaming-chat-model:
#      base-url: http://localhost:11434
#      model-name: deepseek-r1:1.5b
#    embedding-model:
#      base-url: http://localhost:11434
#      model-name: nomic-embed-text:v1.5
langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-b49bab490292431a8ecfce2c6c2f31b9
      model-name: qwen-plus
      log-requests: false
      log-responses: false
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-b49bab490292431a8ecfce2c6c2f31b9
      model-name: qwen-plus
      log-requests: false
      log-responses: false
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v4
      api-key: sk-b49bab490292431a8ecfce2c6c2f31b9
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 外部数据库连接（需要外部MySQL）
    url: jdbc:mysql://mysql:3306/ai_chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      # 外部Redis连接（需要外部Redis）
      host: redis
      port: 6379
      database: 0
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

server:
  port: 8031
  servlet:
    context-path: /api

pinecone:
  api-key: pcsk_3X9iSu_RabFDp8mb3nqD3c9rY52SEWMqfzutSbK2C9CgnA4M3KbMMUYpaN7j2a8o11DWgm
  name-space: testNameSpace
  project-id: 6cfd1c38-64c6-46c8-8fd1-eb541e974364

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml

k8:
  ai:
    base-package: com.k8
    model-key-to-api-key:
      qwen-vl-plus: sk-b49bab490292431a8ecfce2c6c2f31b9
  mcp:
    search:
      model-name: baidu_search_v2
      api-key: bce-v3/ALTAK-ctCacvionwLEhpNZFDupZ/c417857ff7e3a49f829abd45f3b12763e10b03cd
      url: https://qianfan.baidubce.com/v2/ai_search/chat/completions
  static-service:
    # 同一容器内的静态服务地址
    static-server-url: http://localhost:9000
    upload-path: /api/image/upload/direct
    audio-upload-path: /api/audio/upload/direct
  jwt:
    secret-key: k8DefaultSecretKeyForJWTTokenGeneration2025
  tts:
    api-key: sk-b49bab490292431a8ecfce2c6c2f31b9
    model-name: qwen3-tts-flash
    url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
  ars:
    api-key: sk-b49bab490292431a8ecfce2c6c2f31b9
    model-name: paraformer-realtime-v2
    url: https://dashscope.aliyuncs.com/api/v1/services/aigc/speech-recognition/generation
debug: false
