spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always
  data:
    redis:
      # Redis服务器地址
      host: localhost
      # Redis服务器端口
      port: 6379
      # Redis数据库索引（默认为0）
      database: 0
      # 连接超时时间（毫秒）
      timeout: 10000ms
      # 连接池配置
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0

logging:
  level:
    org.springframework.web: DEBUG
    org.apache.tomcat: DEBUG
    com.k8.file: DEBUG

k8:
  static:
    basePath: ./static-files
    host: http://localhost:8080

server:
  port: 9000
  servlet:
    context-path: /
debug: true
